--MAÐAZANIN GÜN BAZLI SATIÞ RAKAMALARINI GETÝRME
SELECT CITY,DATE2,SUM(TOTALPRICE) AS TOTALPRICE
FROM SALES
WHERE CITY ='ANKARA'
GROUP BY CITY,DATE2
ORDER BY CITY,DATE2

--GÜNÜN MAÐAZA BAZLI SATIÞ VERÝLERÝ
SELECT CITY,DATE2,SUM(TOTALPRICE) AS TOTALPRICE
FROM SALES
WHERE DATE2 ='2019-01-01'
GROUP BY DATE2,CITY
ORDER BY DATE2,CITY

--MAÐAZANIN AYLARA GÖRE SATIÞ RAKAMI
SELECT MONTHNAME_,SUM(TOTALPRICE) AS TOTALPRICE 
FROM SALES
GROUP BY MONTHNAME_
ORDER BY MONTHNAME_
UPDATE SALES SET MONTHNAME_='01.OCAK' WHERE DATEPART(MONTH,DATE2)=1
UPDATE SALES SET MONTHNAME_='02.ÞUBAT' WHERE DATEPART(MONTH,DATE2)=2
UPDATE SALES SET MONTHNAME_='03.MART' WHERE DATEPART(MONTH,DATE2)=3
UPDATE SALES SET MONTHNAME_='04.NÝSAN' WHERE DATEPART(MONTH,DATE2)=4
UPDATE SALES SET MONTHNAME_='05.MAYIS' WHERE DATEPART(MONTH,DATE2)=5
UPDATE SALES SET MONTHNAME_='06.HAZÝRAN' WHERE DATEPART(MONTH,DATE2)=6
UPDATE SALES SET MONTHNAME_='07.TEMMUZ' WHERE DATEPART(MONTH,DATE2)=7
UPDATE SALES SET MONTHNAME_='08.AÐUSTOS' WHERE DATEPART(MONTH,DATE2)=8
UPDATE SALES SET MONTHNAME_='09.EYLÜL' WHERE DATEPART(MONTH,DATE2)=9
UPDATE SALES SET MONTHNAME_='10.EKÝM' WHERE DATEPART(MONTH,DATE2)=10
UPDATE SALES SET MONTHNAME_='11.KASIM' WHERE DATEPART(MONTH,DATE2)=11
UPDATE SALES SET MONTHNAME_='12.ARALIK' WHERE DATEPART(MONTH,DATE2)=12

--ÜRÜN KATEGORÝLERÝNE GÖRE SATIÞ RAKAMLARINI GETÝRME
SELECT CATEGORY1,CATEGORY2,CATEGORY3,CATEGORY4,
SUM(TOTALPRICE) AS TOTALPRICE,
COUNT(*) AS ROWCOUNT_,
SUM (AMOUNT) AS TOTALAMOUNT
FROM SALES
GROUP BY CATEGORY1,CATEGORY2,CATEGORY3,CATEGORY4
ORDER BY CATEGORY1,CATEGORY2,CATEGORY3,CATEGORY4

--MAÐAZALARIN MÜÞTERÝ SAYILARINI GETÝRME
SELECT CITY,COUNT(DISTINCT CUSTOMERNAME) AS UNIQUECUSTOMER,
COUNT(DISTINCT FICHENO) CUSTOMERCOUNT,
COUNT(*) ITEMCOUNT
FROM SALES
WHERE MONTHNAME_='01.OCAK'
GROUP BY CITY
ORDER BY CITY

--BELLÝ BÝR CÝRONUN ÜZERÝNDE SATIÞ YAPAN MAÐAZALARI GETÝRME
SELECT CITY,SUM(TOTALPRICE)
FROM SALES
GROUP BY CITY
HAVING SUM(TOTALPRICE)>40000
ORDER BY SUM(TOTALPRICE)