-- Kullanýcý adý,il ,ilçe,semt,adres
--sipariþ ýd ,tarih,toplam tutar,ödeme tarihi,
--banka onay kodu,fatura tarihi,ödeme tarihi
--referans tablomuz ORDERS tablosu
SELECT 
	U.USERNAME_ AS KULLANICIADI,U.NAMESURNAME AS ADSOYAD,
	CT.CITY AS IL,T.TOWN AS ILCE,D.DISTRICT AS SEMT,A.ADDRESSTEXT AS ACIKADRES,
	O.ID AS SIPARISID,O.DATE_ AS TARÝH,O.TOTALPRICE AS TOPLAMTUTAR,
	P.DATE_ AS ODEMETARIHI, P.APPROVECODE AS BANKAONAYKODU,
	I.DATE_ AS FATURATARIHI,I.CARGOFICHENO AS KARGOFISNO,
	ITM.ITEMCODE AS URUNKODU,ITM.ITEMNAME AS URUNADI,OD.AMOUNT AS MIKTAR,OD.UNITPRICE AS BIRIMFÝYAT,
	OD.LINETOTAL AS SATIRTOPLAMI
	
FROM ORDERS O 
	INNER JOIN USERS U ON U.ID=O.USERID
	INNER JOIN ADDRESS A ON A.ID=O.ADDRESSID
	INNER JOIN CITIES CT ON CT.ID=A.CITYID
	INNER JOIN TOWNS T ON T.ID=A.TOWNID
	INNER JOIN DISTRICTS D ON D.ID=A.DISTRICTID
	INNER JOIN PAYMENTS P ON P.ORDERID=O.ID
	INNER JOIN INVOICES I ON I.ORDERID=O.ID
	INNER JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
	INNER JOIN ITEMS ITM ON ITM.ID=OD.ITEMID

WHERE O.ID=3515

--ÞEHÝRLERE GÖRE VERÝLEN TOPLAM SÝPARÝÞ MÝKTARI


SELECT
	CT.CITY AS SEHIRADI,
	SUM(OD.LINETOTAL) AS TOPLAMSIPARISTUTARI,
	SUM(OD.AMOUNT) AS TOPLAMSIPARISADEDI,
	COUNT(OD.ID) AS TOPLAMSIPARISSAYISI,
	

FROM ORDERS O 
	INNER JOIN USERS U ON U.ID=O.USERID
	INNER JOIN ADDRESS A ON A.ID=O.ADDRESSID
	INNER JOIN CITIES CT ON CT.ID=A.CITYID
	INNER JOIN TOWNS T ON T.ID=A.TOWNID
	INNER JOIN DISTRICTS D ON D.ID=A.DISTRICTID
	INNER JOIN PAYMENTS P ON P.ORDERID=O.ID
	INNER JOIN INVOICES I ON I.ORDERID=O.ID
	INNER JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
	INNER JOIN ITEMS ITM ON ITM.ID=OD.ITEMID


GROUP BY CT.CITY
ORDER BY 2 DESC --TOPLAM SÝPARÝÞ TUTARINI BÜYÜKTEN KÜÇÜÐE GETÝRECEK

--ÜRÜN KATEGORÝLERÝNE GÖRE SÝPARÝÞ DAÐILIMI


SELECT
	ITM.CATEGORY1,ITM.CATEGORY2,ITM.CATEGORY3,ITM.CATEGORY4,
	SUM(OD.LINETOTAL) AS TOPLAMSIPARISTUTARI,
	SUM(OD.AMOUNT) AS TOPLAMSIPARISADEDI,
	COUNT(OD.ID) AS TOPLAMSIPARISSAYISI,
	SUM(OD.LINETOTAL)/SUM(OD.AMOUNT) AS ORTALAMABIRIMFIYATI

FROM ORDERS O 
	INNER JOIN USERS U ON U.ID=O.USERID
	INNER JOIN ADDRESS A ON A.ID=O.ADDRESSID
	INNER JOIN CITIES CT ON CT.ID=A.CITYID
	INNER JOIN TOWNS T ON T.ID=A.TOWNID
	INNER JOIN DISTRICTS D ON D.ID=A.DISTRICTID
	INNER JOIN PAYMENTS P ON P.ORDERID=O.ID
	INNER JOIN INVOICES I ON I.ORDERID=O.ID
	INNER JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
	INNER JOIN ITEMS ITM ON ITM.ID=OD.ITEMID

WHERE ITM.CATEGORY1='EV'--EV KATEGORÝSÝNDE NELER SATILMIÞ
GROUP BY ITM.CATEGORY1,ITM.CATEGORY2,ITM.CATEGORY3,ITM.CATEGORY4
ORDER BY 5 DESC

--TARÝHE GÖRE SÝPARÝÞ DAÐILIMI

SELECT
DATEPART(YEAR,O.DATE_) AS YIL,
DATEPART(MONTH,O.DATE_) AS AY, -- AYLARA GÖRE SIRALAMAK ÝÇÝN DATEPART KOMUTUNU KULLANDIK.
SUM(OD.LINETOTAL) AS TOPLAMSIPARISTUTAR,
SUM(OD.AMOUNT)AS TOPLAMSIPARISMIKTAR,
COUNT(OD.ID) AS TOPLAMSIPARISSAYISI

FROM ORDERS O 
	INNER JOIN USERS U ON U.ID=O.USERID
	INNER JOIN ADDRESS A ON A.ID=O.ADDRESSID
	INNER JOIN CITIES CT ON CT.ID=A.CITYID
	INNER JOIN TOWNS T ON T.ID=A.TOWNID
	INNER JOIN DISTRICTS D ON D.ID=A.DISTRICTID
	INNER JOIN PAYMENTS P ON P.ORDERID=O.ID
	INNER JOIN INVOICES I ON I.ORDERID=O.ID
	INNER JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
	INNER JOIN ITEMS ITM ON ITM.ID=OD.ITEMID

GROUP BY DATEPART(MONTH,O.DATE_),DATEPART(YEAR,O.DATE_) 
ORDER BY DATEPART(MONTH,O.DATE_),DATEPART(YEAR,O.DATE_) 

--ÖDEME TÜRÜNE GÖRE DAÐILIM

SELECT
PAYMENTTYPE AS ODEMETURU,
CASE -- CASE WHEN METODU 1 YERÝNE ÖDEME TÜRÜNÜ YAZDIRMAMIZI SAÐLADI.
	WHEN PAYMENTTYPE=1 THEN 'KREDÝ KARTI'
	WHEN PAYMENTTYPE=2 THEN 'BANKA HAVALESÝ'
	END AS ODEMETURUACIKLAMA,
SUM(PAYMENTTOTAL) AS TOPLAMTUTAR
FROM PAYMENTS
GROUP BY PAYMENTTYPE 