
SELECT CITY, DATE2,SUM(TOTALPRICE) AS TOTALPRICE

FROM SALES WHERE CITY='ANKARA'
GROUP BY CITY,DATE2
ORDER BY CITY,DATE2
AND DATE2='2019-01-01'
ORDER BY DATE_


UPDATE SALES SET DATE2=CONVERT(DATE,DATE_)